#pragma once

#define DYNAMIC_KEYMAP_MACRO_COUNT 128

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT LAYERS_SIZE

#define VADIMVOLK_LAYOUT

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_NONE
