#pragma once

#define DYNAMIC_KEYMAP_MACRO_COUNT 128

#undef DYNAMIC_KEYMAP_LAYER_COUNT
#define DYNAMIC_KEYMAP_LAYER_COUNT 8

#define VADIMVOLK_LAYOUT

#undef RGB_MATRIX_DEFAULT_MODE
#define RGB_MATRIX_DEFAULT_MODE RGB_MATRIX_NONE

#define PERMISSIVE_HOLD
#define TAPPING_TERM 2000

#define KC_LAUNCHER KC_F20